import type { ThemePreset, ThemeTokens } from '../types'

const common: Readonly<ThemeTokens> = Object.freeze({
  colorPrimaryPressed: '#5b21b6',
  colorPrimaryDisabled: '#aa92cd',
  colorPrimaryFocus: '#9672d0',
  colorAccent: '#6d28d9',
  colorTextDisabled: '#a48cbf',
  colorWarningPressed: '#c58e12',
  colorWarningDisabled: '#dfc58b',
  colorSuccessPressed: '#21885c',
  colorSuccessDisabled: '#93cbb2',
  colorErrorPressed: '#c9444b',
  colorErrorDisabled: '#e6abae',
  colorPrimary: '#7c3aed',
  colorPrimaryHover: '#6d28d9',
  colorOnPrimary: '#ffffff',
  colorSuccess: '#34b27b',
  colorSuccessHover: '#299f6c',
  colorOnSuccess: '#ffffff',
  colorWarning: '#f0b429',
  colorWarningHover: '#dea41d',
  colorOnWarning: '#ffffff',
  colorError: '#f06468',
  colorErrorHover: '#df5359',
  colorOnError: '#ffffff',
  colorText: '#332547',
  colorTextMuted: '#746a83',
  colorSurface: '#ffffff',
  colorSurfaceRaised: '#ffffff',
  colorSurfaceHover: '#f1ebfc',
  colorBorder: '#d8cce8',
  colorBorderStrong: '#d8cce8',
  radiusMedium: '6px',
  space2: '8px',
  space3: '12px',
  space4: '16px',
  space5: '20px',
  durationFast: '150ms',
  heightSmall: '28px',
  heightMedium: '34px',
  heightLarge: '40px',
  fontSizeSmall: '14px',
  fontSizeMedium: '14px',
  fontSizeLarge: '14px',
  fontWeightStrong: '500',
  opacityDisabled: '1',
  durationSpin: '0.8s',
})

export const lightPreset: ThemePreset = Object.freeze({ name: 'light', common })
export type { ThemePreset } from '../types'
